ALTER TABLE `mail`
    CHANGE COLUMN `body` `mailTextId` INT UNSIGNED NOT NULL DEFAULT '0' AFTER `subject`;

CREATE TABLE `mail_text` (
    `id` INT UNSIGNED NOT NULL DEFAULT '0',
    `body` LONGTEXT,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
