ALTER TABLE `spell_dbc`
    DROP COLUMN `AttributesEx7`,
    DROP COLUMN `EffectSpellClassMaskA1`,
    DROP COLUMN `EffectSpellClassMaskA2`,
    DROP COLUMN `EffectSpellClassMaskA3`,
    DROP COLUMN `EffectSpellClassMaskB1`,
    DROP COLUMN `EffectSpellClassMaskB2`,
    DROP COLUMN `EffectSpellClassMaskB3`,
    DROP COLUMN `EffectSpellClassMaskC1`,
    DROP COLUMN `EffectSpellClassMaskC2`,
    DROP COLUMN `EffectSpellClassMaskC3`,
    DROP COLUMN `SpellFamilyFlags2`,
    DROP COLUMN `SpellFamilyFlags3`;
