ALTER TABLE `instance_encounters`
    ADD COLUMN `mapId` INT(10) UNSIGNED NOT NULL AFTER `lastEncounterDungeon`,
    ADD COLUMN `difficulty` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' AFTER `mapId`,
    ADD COLUMN `encounterIndex` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER `difficulty`,
    ADD COLUMN `encounterName` VARCHAR(255) NOT NULL DEFAULT '' AFTER `encounterIndex`;

DELETE FROM `instance_encounters` WHERE `entry` IN (567, 568, 674, 678, 680, 682, 684, 686, 689, 691, 693, 695, 697, 699, 701, 703, 706);

UPDATE `instance_encounters` SET `mapId`=36, `encounterName`='Rhahk''zor' WHERE `entry`=161;
UPDATE `instance_encounters` SET `mapId`=36, `encounterIndex`=1, `encounterName`='Sneed' WHERE `entry`=162;
UPDATE `instance_encounters` SET `mapId`=36, `encounterIndex`=2, `encounterName`='Gilnid' WHERE `entry`=163;
UPDATE `instance_encounters` SET `mapId`=36, `encounterIndex`=3, `encounterName`='Mr. Smite' WHERE `entry`=164;
UPDATE `instance_encounters` SET `mapId`=36, `encounterIndex`=4, `encounterName`='Cookie' WHERE `entry`=165;
UPDATE `instance_encounters` SET `mapId`=36, `encounterIndex`=5, `encounterName`='Captain Greenskin' WHERE `entry`=166;
UPDATE `instance_encounters` SET `mapId`=36, `encounterIndex`=6, `encounterName`='Edwin VanCleef' WHERE `entry`=167;
UPDATE `instance_encounters` SET `mapId`=558, `encounterName`='Shirrak the Dead Watcher' WHERE `entry`=201;
UPDATE `instance_encounters` SET `mapId`=558, `encounterIndex`=1, `encounterName`='Exarch Maladaar' WHERE `entry`=202;
UPDATE `instance_encounters` SET `mapId`=557, `encounterName`='Pandemonius' WHERE `entry`=203;
UPDATE `instance_encounters` SET `mapId`=557, `encounterIndex`=1, `encounterName`='Tavarok' WHERE `entry`=204;
UPDATE `instance_encounters` SET `mapId`=557, `encounterIndex`=2, `encounterName`='Nexus-Prince Shaffar' WHERE `entry`=205;
UPDATE `instance_encounters` SET `mapId`=556, `encounterName`='Darkweaver Syth' WHERE `entry`=206;
UPDATE `instance_encounters` SET `mapId`=556, `encounterIndex`=1, `encounterName`='Talon King Ikiss' WHERE `entry`=207;
UPDATE `instance_encounters` SET `mapId`=555, `encounterName`='Ambassador Hellmaw' WHERE `entry`=208;
UPDATE `instance_encounters` SET `mapId`=555, `encounterIndex`=1, `encounterName`='Blackheart the Inciter' WHERE `entry`=209;
UPDATE `instance_encounters` SET `mapId`=555, `encounterIndex`=2, `encounterName`='Grandmaster Vorpil' WHERE `entry`=210;
UPDATE `instance_encounters` SET `mapId`=555, `encounterIndex`=3, `encounterName`='Murmur' WHERE `entry`=211;
UPDATE `instance_encounters` SET `mapId`=48, `encounterName`='Ghamoo-ra' WHERE `entry`=219;
UPDATE `instance_encounters` SET `mapId`=48, `encounterIndex`=1, `encounterName`='Lady Sarevess' WHERE `entry`=220;
UPDATE `instance_encounters` SET `mapId`=48, `encounterIndex`=2, `encounterName`='Gelihast' WHERE `entry`=221;
UPDATE `instance_encounters` SET `mapId`=48, `encounterIndex`=3, `encounterName`='Lorgus Jett' WHERE `entry`=222;
UPDATE `instance_encounters` SET `mapId`=48, `encounterIndex`=5, `encounterName`='Old Serra''kis' WHERE `entry`=224;
UPDATE `instance_encounters` SET `mapId`=48, `encounterIndex`=6, `encounterName`='Twilight Lord Kelris' WHERE `entry`=225;
UPDATE `instance_encounters` SET `mapId`=48, `encounterIndex`=7, `encounterName`='Aku''mai' WHERE `entry`=226;
UPDATE `instance_encounters` SET `mapId`=230, `encounterName`='High Interrogator Gerstahn' WHERE `entry`=227;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=1, `encounterName`='Lord Roccor' WHERE `entry`=228;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=2, `encounterName`='Houndmaster Grebmar' WHERE `entry`=229;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=3, `encounterName`='Ring of Law' WHERE `entry`=230;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=4, `encounterName`='Pyromancer Loregrain' WHERE `entry`=231;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=5, `encounterName`='Lord Incendius' WHERE `entry`=232;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=6, `encounterName`='Warder Stilgiss' WHERE `entry`=233;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=7, `encounterName`='Fineous Darkvire' WHERE `entry`=234;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=8, `encounterName`='Bael''Gar' WHERE `entry`=235;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=9, `encounterName`='General Angerforge' WHERE `entry`=236;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=10, `encounterName`='Golem Lord Argelmach' WHERE `entry`=237;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=11, `encounterName`='Hurley Blackbreath' WHERE `entry`=238;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=12, `encounterName`='Phalanx' WHERE `entry`=239;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=13, `encounterName`='Ribbly Screwspigot' WHERE `entry`=240;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=14, `encounterName`='Plugger Spazzring' WHERE `entry`=241;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=15, `encounterName`='Ambassador Flamelash' WHERE `entry`=242;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=16, `encounterName`='The Seven' WHERE `entry`=243;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=17, `encounterName`='Magmus' WHERE `entry`=244;
UPDATE `instance_encounters` SET `mapId`=230, `encounterIndex`=18, `encounterName`='Emperor Dagran Thaurissan' WHERE `entry`=245;
UPDATE `instance_encounters` SET `mapId`=558, `difficulty`=1, `encounterName`='Shirrak the Dead Watcher' WHERE `entry`=246;
UPDATE `instance_encounters` SET `mapId`=558, `difficulty`=1, `encounterIndex`=1, `encounterName`='Exarch Maladaar' WHERE `entry`=247;
UPDATE `instance_encounters` SET `mapId`=557, `difficulty`=1, `encounterName`='Pandemonius' WHERE `entry`=248;
UPDATE `instance_encounters` SET `mapId`=557, `difficulty`=1, `encounterIndex`=1, `encounterName`='Tavarok' WHERE `entry`=249;
UPDATE `instance_encounters` SET `mapId`=557, `difficulty`=1, `encounterIndex`=2, `encounterName`='Yor' WHERE `entry`=250;
UPDATE `instance_encounters` SET `mapId`=557, `difficulty`=1, `encounterIndex`=3, `encounterName`='Nexus-Prince Shaffar' WHERE `entry`=251;
UPDATE `instance_encounters` SET `mapId`=556, `difficulty`=1, `encounterName`='Darkweaver Syth' WHERE `entry`=252;
UPDATE `instance_encounters` SET `mapId`=556, `difficulty`=1, `encounterIndex`=1, `encounterName`='Anzu' WHERE `entry`=253;
UPDATE `instance_encounters` SET `mapId`=556, `difficulty`=1, `encounterIndex`=2, `encounterName`='Talon King Ikiss' WHERE `entry`=254;
UPDATE `instance_encounters` SET `mapId`=555, `difficulty`=1, `encounterName`='Ambassador Hellmaw' WHERE `entry`=255;
UPDATE `instance_encounters` SET `mapId`=555, `difficulty`=1, `encounterIndex`=1, `encounterName`='Blackheart the Inciter' WHERE `entry`=256;
UPDATE `instance_encounters` SET `mapId`=555, `difficulty`=1, `encounterIndex`=2, `encounterName`='Grandmaster Vorpil' WHERE `entry`=257;
UPDATE `instance_encounters` SET `mapId`=555, `difficulty`=1, `encounterIndex`=3, `encounterName`='Murmur' WHERE `entry`=258;
UPDATE `instance_encounters` SET `mapId`=229, `encounterName`='Highlord Omokk' WHERE `entry`=267;
UPDATE `instance_encounters` SET `mapId`=229, `encounterIndex`=1, `encounterName`='Shadow Hunter Vosh''gajin' WHERE `entry`=268;
UPDATE `instance_encounters` SET `mapId`=229, `encounterIndex`=2, `encounterName`='War Master Voone' WHERE `entry`=269;
UPDATE `instance_encounters` SET `mapId`=229, `encounterIndex`=3, `encounterName`='Mother Smolderweb' WHERE `entry`=270;
UPDATE `instance_encounters` SET `mapId`=229, `encounterIndex`=4, `encounterName`='Urok Doomhowl' WHERE `entry`=271;
UPDATE `instance_encounters` SET `mapId`=229, `encounterIndex`=5, `encounterName`='Quartermaster Zigris' WHERE `entry`=272;
UPDATE `instance_encounters` SET `mapId`=229, `encounterIndex`=6, `encounterName`='Gizrul the Slavener' WHERE `entry`=273;
UPDATE `instance_encounters` SET `mapId`=229, `encounterIndex`=7, `encounterName`='Halycon' WHERE `entry`=274;
UPDATE `instance_encounters` SET `mapId`=229, `encounterIndex`=8, `encounterName`='Overlord Wyrmthalak' WHERE `entry`=275;
UPDATE `instance_encounters` SET `mapId`=229, `encounterIndex`=9, `encounterName`='Pyroguard Emberseer' WHERE `entry`=276;
UPDATE `instance_encounters` SET `mapId`=229, `encounterIndex`=10, `encounterName`='Solakar Flamewreath' WHERE `entry`=277;
UPDATE `instance_encounters` SET `mapId`=229, `encounterIndex`=11, `encounterName`='Warchief Rend Blackhand' WHERE `entry`=278;
UPDATE `instance_encounters` SET `mapId`=229, `encounterIndex`=12, `encounterName`='The Beast' WHERE `entry`=279;
UPDATE `instance_encounters` SET `mapId`=229, `encounterIndex`=13, `encounterName`='General Drakkisath' WHERE `entry`=280;
UPDATE `instance_encounters` SET `mapId`=560, `encounterName`='Epoch Hunter' WHERE `entry`=281;
UPDATE `instance_encounters` SET `mapId`=560, `difficulty`=1, `encounterName`='Epoch Hunter' WHERE `entry`=282;
UPDATE `instance_encounters` SET `mapId`=560, `encounterIndex`=1, `encounterName`='Captain Skarloc' WHERE `entry`=283;
UPDATE `instance_encounters` SET `mapId`=560, `difficulty`=1, `encounterIndex`=1, `encounterName`='Captain Skarloc' WHERE `entry`=284;
UPDATE `instance_encounters` SET `mapId`=560, `encounterIndex`=2, `encounterName`='Lieutenant Drake' WHERE `entry`=285;
UPDATE `instance_encounters` SET `mapId`=560, `difficulty`=1, `encounterIndex`=2, `encounterName`='Lieutenant Drake' WHERE `entry`=286;
UPDATE `instance_encounters` SET `mapId`=269, `encounterName`='Chrono Lord Deja' WHERE `entry`=287;
UPDATE `instance_encounters` SET `mapId`=269, `difficulty`=1, `encounterName`='Chrono Lord Deja' WHERE `entry`=288;
UPDATE `instance_encounters` SET `mapId`=269, `encounterIndex`=1, `encounterName`='Temporus' WHERE `entry`=289;
UPDATE `instance_encounters` SET `mapId`=269, `difficulty`=1, `encounterIndex`=1, `encounterName`='Temporus' WHERE `entry`=290;
UPDATE `instance_encounters` SET `mapId`=269, `encounterIndex`=2, `encounterName`='Aeonus' WHERE `entry`=291;
UPDATE `instance_encounters` SET `mapId`=269, `difficulty`=1, `encounterIndex`=2, `encounterName`='Aeonus' WHERE `entry`=292;
UPDATE `instance_encounters` SET `mapId`=547, `encounterName`='Mennu the Betrayer' WHERE `entry`=301;
UPDATE `instance_encounters` SET `mapId`=547, `encounterIndex`=1, `encounterName`='Rokmar the Crackler' WHERE `entry`=302;
UPDATE `instance_encounters` SET `mapId`=547, `encounterIndex`=2, `encounterName`='Quagmirran' WHERE `entry`=303;
UPDATE `instance_encounters` SET `mapId`=547, `difficulty`=1, `encounterName`='Mennu the Betrayer' WHERE `entry`=304;
UPDATE `instance_encounters` SET `mapId`=547, `difficulty`=1, `encounterIndex`=1, `encounterName`='Rokmar the Crackler' WHERE `entry`=305;
UPDATE `instance_encounters` SET `mapId`=547, `difficulty`=1, `encounterIndex`=2, `encounterName`='Quagmirran' WHERE `entry`=306;
UPDATE `instance_encounters` SET `mapId`=545, `encounterName`='Hydromancer Thespia' WHERE `entry`=314;
UPDATE `instance_encounters` SET `mapId`=545, `difficulty`=1, `encounterName`='Hydromancer Thespia' WHERE `entry`=315;
UPDATE `instance_encounters` SET `mapId`=545, `encounterIndex`=1, `encounterName`='Mekgineer Steamrigger' WHERE `entry`=316;
UPDATE `instance_encounters` SET `mapId`=545, `difficulty`=1, `encounterIndex`=1, `encounterName`='Mekgineer Steamrigger' WHERE `entry`=317;
UPDATE `instance_encounters` SET `mapId`=545, `encounterIndex`=2, `encounterName`='Warlord Kalithresh' WHERE `entry`=318;
UPDATE `instance_encounters` SET `mapId`=545, `difficulty`=1, `encounterIndex`=2, `encounterName`='Warlord Kalithresh' WHERE `entry`=319;
UPDATE `instance_encounters` SET `mapId`=546, `encounterName`='Hungarfen' WHERE `entry`=320;
UPDATE `instance_encounters` SET `mapId`=546, `difficulty`=1, `encounterName`='Hungarfen' WHERE `entry`=321;
UPDATE `instance_encounters` SET `mapId`=546, `encounterIndex`=1, `encounterName`='Ghaz''an' WHERE `entry`=322;
UPDATE `instance_encounters` SET `mapId`=546, `difficulty`=1, `encounterIndex`=1, `encounterName`='Ghaz''an' WHERE `entry`=323;
UPDATE `instance_encounters` SET `mapId`=546, `encounterIndex`=2, `encounterName`='Swamplord Musel''ek' WHERE `entry`=329;
UPDATE `instance_encounters` SET `mapId`=546, `difficulty`=1, `encounterIndex`=2, `encounterName`='Swamplord Musel''ek' WHERE `entry`=330;
UPDATE `instance_encounters` SET `mapId`=546, `encounterIndex`=3, `encounterName`='The Black Stalker' WHERE `entry`=331;
UPDATE `instance_encounters` SET `mapId`=546, `difficulty`=1, `encounterIndex`=3, `encounterName`='The Black Stalker' WHERE `entry`=332;
UPDATE `instance_encounters` SET `mapId`=429, `encounterName`='Zevrim Thornhoof' WHERE `entry`=343;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=1, `encounterName`='Hydrospawn' WHERE `entry`=344;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=2, `encounterName`='Lethtendris' WHERE `entry`=345;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=3, `encounterName`='Alzzin the Wildshaper' WHERE `entry`=346;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=4, `encounterName`='Illyanna Ravenoak' WHERE `entry`=347;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=5, `encounterName`='Magister Kalendris' WHERE `entry`=348;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=6, `encounterName`='Immol''thar' WHERE `entry`=349;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=7, `encounterName`='Tendris Warpwood' WHERE `entry`=350;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=8, `encounterName`='Prince Tortheldrin' WHERE `entry`=361;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=9, `encounterName`='Guard Mol''dar' WHERE `entry`=362;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=10, `encounterName`='Stomper Kreeg' WHERE `entry`=363;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=11, `encounterName`='Guard Fengus' WHERE `entry`=364;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=12, `encounterName`='Guard Slip''kik' WHERE `entry`=365;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=13, `encounterName`='Captain Kromcrush' WHERE `entry`=366;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=14, `encounterName`='Cho''Rush the Observer' WHERE `entry`=367;
UPDATE `instance_encounters` SET `mapId`=429, `encounterIndex`=15, `encounterName`='King Gordok' WHERE `entry`=368;
UPDATE `instance_encounters` SET `mapId`=90, `encounterIndex`=1, `encounterName`='Viscous Fallout' WHERE `entry`=378;
UPDATE `instance_encounters` SET `mapId`=90, `encounterIndex`=2, `encounterName`='Grubbis' WHERE `entry`=379;
UPDATE `instance_encounters` SET `mapId`=90, `encounterIndex`=3, `encounterName`='Electrocutioner 6000' WHERE `entry`=380;
UPDATE `instance_encounters` SET `mapId`=90, `encounterIndex`=4, `encounterName`='Crowd Pummeler 9-60' WHERE `entry`=381;
UPDATE `instance_encounters` SET `mapId`=90, `encounterIndex`=5, `encounterName`='Mekgineer Thermaplugg' WHERE `entry`=382;
UPDATE `instance_encounters` SET `mapId`=543, `encounterName`='Watchkeeper Gargolmar' WHERE `entry`=392;
UPDATE `instance_encounters` SET `mapId`=543, `difficulty`=1, `encounterName`='Watchkeeper Gargolmar' WHERE `entry`=393;
UPDATE `instance_encounters` SET `mapId`=543, `encounterIndex`=1, `encounterName`='Omor the Unscarred' WHERE `entry`=394;
UPDATE `instance_encounters` SET `mapId`=543, `difficulty`=1, `encounterIndex`=1, `encounterName`='Omor the Unscarred' WHERE `entry`=395;
UPDATE `instance_encounters` SET `mapId`=543, `encounterIndex`=2, `encounterName`='Vazruden the Herald' WHERE `entry`=396;
UPDATE `instance_encounters` SET `mapId`=543, `difficulty`=1, `encounterIndex`=2, `encounterName`='Vazruden the Herald' WHERE `entry`=397;
UPDATE `instance_encounters` SET `mapId`=542, `encounterName`='The Maker' WHERE `entry`=401;
UPDATE `instance_encounters` SET `mapId`=542, `difficulty`=1, `encounterName`='The Maker' WHERE `entry`=402;
UPDATE `instance_encounters` SET `mapId`=542, `encounterIndex`=1, `encounterName`='Broggok' WHERE `entry`=403;
UPDATE `instance_encounters` SET `mapId`=542, `difficulty`=1, `encounterIndex`=1, `encounterName`='Broggok' WHERE `entry`=404;
UPDATE `instance_encounters` SET `mapId`=542, `encounterIndex`=2, `encounterName`='Keli''dan the Breaker' WHERE `entry`=405;
UPDATE `instance_encounters` SET `mapId`=542, `difficulty`=1, `encounterIndex`=2, `encounterName`='Keli''dan the Breaker' WHERE `entry`=406;
UPDATE `instance_encounters` SET `mapId`=540, `encounterName`='Grand Warlock Nethekurse' WHERE `entry`=407;
UPDATE `instance_encounters` SET `mapId`=540, `difficulty`=1, `encounterName`='Grand Warlock Nethekurse' WHERE `entry`=408;
UPDATE `instance_encounters` SET `mapId`=540, `difficulty`=1, `encounterIndex`=1, `encounterName`='Blood Guard Porung' WHERE `entry`=409;
UPDATE `instance_encounters` SET `mapId`=540, `encounterIndex`=1, `encounterName`='Warbringer O''mrogg' WHERE `entry`=410;
UPDATE `instance_encounters` SET `mapId`=540, `difficulty`=1, `encounterIndex`=2, `encounterName`='Warbringer O''mrogg' WHERE `entry`=411;
UPDATE `instance_encounters` SET `mapId`=540, `encounterIndex`=2, `encounterName`='Warchief Kargath Bladefist' WHERE `entry`=412;
UPDATE `instance_encounters` SET `mapId`=540, `difficulty`=1, `encounterIndex`=3, `encounterName`='Warchief Kargath Bladefist' WHERE `entry`=413;
UPDATE `instance_encounters` SET `mapId`=585, `encounterName`='Selin Fireheart' WHERE `entry`=414;
UPDATE `instance_encounters` SET `mapId`=585, `difficulty`=1, `encounterName`='Selin Fireheart' WHERE `entry`=415;
UPDATE `instance_encounters` SET `mapId`=585, `encounterIndex`=1, `encounterName`='Vexallus' WHERE `entry`=416;
UPDATE `instance_encounters` SET `mapId`=585, `difficulty`=1, `encounterIndex`=1, `encounterName`='Vexallus' WHERE `entry`=417;
UPDATE `instance_encounters` SET `mapId`=585, `encounterIndex`=2, `encounterName`='Priestess Delrissa' WHERE `entry`=418;
UPDATE `instance_encounters` SET `mapId`=585, `difficulty`=1, `encounterIndex`=2, `encounterName`='Priestess Delrissa' WHERE `entry`=419;
UPDATE `instance_encounters` SET `mapId`=585, `encounterIndex`=3, `encounterName`='Kael''thas Sunstrider' WHERE `entry`=420;
UPDATE `instance_encounters` SET `mapId`=585, `difficulty`=1, `encounterIndex`=3, `encounterName`='Kael''thas Sunstrider' WHERE `entry`=421;
UPDATE `instance_encounters` SET `mapId`=349, `encounterName`='Noxxion' WHERE `entry`=422;
UPDATE `instance_encounters` SET `mapId`=349, `encounterIndex`=1, `encounterName`='Razorlash' WHERE `entry`=423;
UPDATE `instance_encounters` SET `mapId`=349, `encounterIndex`=2, `encounterName`='Lord Vyletongue' WHERE `entry`=424;
UPDATE `instance_encounters` SET `mapId`=349, `encounterIndex`=3, `encounterName`='Celebras the Cursed' WHERE `entry`=425;
UPDATE `instance_encounters` SET `mapId`=349, `encounterIndex`=4, `encounterName`='Landslide' WHERE `entry`=426;
UPDATE `instance_encounters` SET `mapId`=349, `encounterIndex`=5, `encounterName`='Tinkerer Gizlock' WHERE `entry`=427;
UPDATE `instance_encounters` SET `mapId`=349, `encounterIndex`=6, `encounterName`='Rotgrip' WHERE `entry`=428;
UPDATE `instance_encounters` SET `mapId`=349, `encounterIndex`=7, `encounterName`='Princess Theradras' WHERE `entry`=429;
UPDATE `instance_encounters` SET `mapId`=389, `encounterName`='Oggleflint' WHERE `entry`=430;
UPDATE `instance_encounters` SET `mapId`=389, `encounterIndex`=1, `encounterName`='Taragaman the Hungerer' WHERE `entry`=431;
UPDATE `instance_encounters` SET `mapId`=389, `encounterIndex`=2, `encounterName`='Jergosh the Invoker' WHERE `entry`=432;
UPDATE `instance_encounters` SET `mapId`=389, `encounterIndex`=3, `encounterName`='Bazzalan' WHERE `entry`=433;
UPDATE `instance_encounters` SET `mapId`=129, `encounterName`='Tuten''kash' WHERE `entry`=434;
UPDATE `instance_encounters` SET `mapId`=129, `encounterIndex`=1, `encounterName`='Mordresh Fire Eye' WHERE `entry`=435;
UPDATE `instance_encounters` SET `mapId`=129, `encounterIndex`=2, `encounterName`='Glutton' WHERE `entry`=436;
UPDATE `instance_encounters` SET `mapId`=129, `encounterIndex`=3, `encounterName`='Amnennar the Coldbringer' WHERE `entry`=437;
UPDATE `instance_encounters` SET `mapId`=47, `encounterName`='Roogug' WHERE `entry`=438;
UPDATE `instance_encounters` SET `mapId`=47, `encounterIndex`=1, `encounterName`='Aggem Thorncurse' WHERE `entry`=439;
UPDATE `instance_encounters` SET `mapId`=47, `encounterIndex`=2, `encounterName`='Death Speaker Jargba' WHERE `entry`=440;
UPDATE `instance_encounters` SET `mapId`=47, `encounterIndex`=3, `encounterName`='Overlord Ramtusk' WHERE `entry`=441;
UPDATE `instance_encounters` SET `mapId`=47, `encounterIndex`=4, `encounterName`='Charlga Razorflank' WHERE `entry`=443;
UPDATE `instance_encounters` SET `mapId`=189, `encounterName`='Interrogator Vishas' WHERE `entry`=444;
UPDATE `instance_encounters` SET `mapId`=189, `encounterIndex`=1, `encounterName`='Bloodmage Thalnos' WHERE `entry`=445;
UPDATE `instance_encounters` SET `mapId`=189, `encounterIndex`=2, `encounterName`='Houndmaster Loksey' WHERE `entry`=446;
UPDATE `instance_encounters` SET `mapId`=189, `encounterIndex`=3, `encounterName`='Arcanist Doan' WHERE `entry`=447;
UPDATE `instance_encounters` SET `mapId`=189, `encounterIndex`=4, `encounterName`='Herod' WHERE `entry`=448;
UPDATE `instance_encounters` SET `mapId`=189, `encounterIndex`=5, `encounterName`='High Inquisitor Fairbanks' WHERE `entry`=449;
UPDATE `instance_encounters` SET `mapId`=189, `encounterIndex`=6, `encounterName`='High Inquisitor Whitemane' WHERE `entry`=450;
UPDATE `instance_encounters` SET `mapId`=289, `encounterName`='Kirtonos the Herald' WHERE `entry`=451;
UPDATE `instance_encounters` SET `mapId`=289, `encounterIndex`=1, `encounterName`='Jandice Barov' WHERE `entry`=452;
UPDATE `instance_encounters` SET `mapId`=289, `encounterIndex`=2, `encounterName`='Rattlegore' WHERE `entry`=453;
UPDATE `instance_encounters` SET `mapId`=289, `encounterIndex`=3, `encounterName`='Marduk Blackpool' WHERE `entry`=454;
UPDATE `instance_encounters` SET `mapId`=289, `encounterIndex`=4, `encounterName`='Vectus' WHERE `entry`=455;
UPDATE `instance_encounters` SET `mapId`=289, `encounterIndex`=5, `encounterName`='Ras Frostwhisper' WHERE `entry`=456;
UPDATE `instance_encounters` SET `mapId`=289, `encounterIndex`=6, `encounterName`='Instructor Malicia' WHERE `entry`=457;
UPDATE `instance_encounters` SET `mapId`=289, `encounterIndex`=7, `encounterName`='Doctor Theolen Krastinov' WHERE `entry`=458;
UPDATE `instance_encounters` SET `mapId`=289, `encounterIndex`=8, `encounterName`='Lorekeeper Polkelt' WHERE `entry`=459;
UPDATE `instance_encounters` SET `mapId`=289, `encounterIndex`=9, `encounterName`='The Ravenian' WHERE `entry`=460;
UPDATE `instance_encounters` SET `mapId`=289, `encounterIndex`=10, `encounterName`='Lord Alexei Barov' WHERE `entry`=461;
UPDATE `instance_encounters` SET `mapId`=289, `encounterIndex`=11, `encounterName`='Lady Illucia Barov' WHERE `entry`=462;
UPDATE `instance_encounters` SET `mapId`=289, `encounterIndex`=12, `encounterName`='Darkmaster Gandling' WHERE `entry`=463;
UPDATE `instance_encounters` SET `mapId`=33, `encounterName`='Rethilgore' WHERE `entry`=464;
UPDATE `instance_encounters` SET `mapId`=33, `encounterIndex`=1, `encounterName`='Razorclaw the Butcher' WHERE `entry`=465;
UPDATE `instance_encounters` SET `mapId`=33, `encounterIndex`=2, `encounterName`='Baron Silverlaine' WHERE `entry`=466;
UPDATE `instance_encounters` SET `mapId`=33, `encounterIndex`=3, `encounterName`='Commander Springvale' WHERE `entry`=467;
UPDATE `instance_encounters` SET `mapId`=33, `encounterIndex`=4, `encounterName`='Odo the Blindwatcher' WHERE `entry`=468;
UPDATE `instance_encounters` SET `mapId`=33, `encounterIndex`=5, `encounterName`='Fenrus the Devourer' WHERE `entry`=469;
UPDATE `instance_encounters` SET `mapId`=33, `encounterIndex`=6, `encounterName`='Wolf Master Nandos' WHERE `entry`=470;
UPDATE `instance_encounters` SET `mapId`=33, `encounterIndex`=7, `encounterName`='Archmage Arugal' WHERE `entry`=471;
UPDATE `instance_encounters` SET `mapId`=329, `encounterName`='The Unforgiven' WHERE `entry`=472;
UPDATE `instance_encounters` SET `mapId`=329, `encounterIndex`=1, `encounterName`='Hearthsinger Forresten' WHERE `entry`=473;
UPDATE `instance_encounters` SET `mapId`=329, `encounterIndex`=2, `encounterName`='Timmy the Cruel' WHERE `entry`=474;
UPDATE `instance_encounters` SET `mapId`=329, `encounterIndex`=3, `encounterName`='Cannon Master Willey' WHERE `entry`=475;
UPDATE `instance_encounters` SET `mapId`=329, `encounterIndex`=4, `encounterName`='Malor the Zealous' WHERE `entry`=476;
UPDATE `instance_encounters` SET `mapId`=329, `encounterIndex`=5, `encounterName`='Archivist Galford' WHERE `entry`=477;
UPDATE `instance_encounters` SET `mapId`=329, `encounterIndex`=6, `encounterName`='Balnazzar' WHERE `entry`=478;
UPDATE `instance_encounters` SET `mapId`=329, `encounterIndex`=7, `encounterName`='Baroness Anastari' WHERE `entry`=479;
UPDATE `instance_encounters` SET `mapId`=329, `encounterIndex`=8, `encounterName`='Nerub''enkan' WHERE `entry`=480;
UPDATE `instance_encounters` SET `mapId`=329, `encounterIndex`=9, `encounterName`='Maleki the Pallid' WHERE `entry`=481;
UPDATE `instance_encounters` SET `mapId`=329, `encounterIndex`=10, `encounterName`='Magistrate Barthilas' WHERE `entry`=482;
UPDATE `instance_encounters` SET `mapId`=329, `encounterIndex`=11, `encounterName`='Ramnstein the Gorger' WHERE `entry`=483;
UPDATE `instance_encounters` SET `mapId`=329, `encounterIndex`=12, `encounterName`='Baron Rivendare' WHERE `entry`=484;
UPDATE `instance_encounters` SET `mapId`=109, `encounterName`='Atal''alarion' WHERE `entry`=485;
UPDATE `instance_encounters` SET `mapId`=109, `encounterIndex`=1, `encounterName`='Dreamscythe' WHERE `entry`=486;
UPDATE `instance_encounters` SET `mapId`=109, `encounterIndex`=2, `encounterName`='Weaver' WHERE `entry`=487;
UPDATE `instance_encounters` SET `mapId`=109, `encounterIndex`=3, `encounterName`='Jammal''an the Prophet' WHERE `entry`=488;
UPDATE `instance_encounters` SET `mapId`=109, `encounterIndex`=5, `encounterName`='Morphaz' WHERE `entry`=490;
UPDATE `instance_encounters` SET `mapId`=109, `encounterIndex`=6, `encounterName`='Hazzas' WHERE `entry`=491;
UPDATE `instance_encounters` SET `mapId`=109, `encounterIndex`=7, `encounterName`='Avatar of Hakkar' WHERE `entry`=492;
UPDATE `instance_encounters` SET `mapId`=109, `encounterIndex`=8, `encounterName`='Shade of Eranikus' WHERE `entry`=493;
UPDATE `instance_encounters` SET `mapId`=552, `encounterName`='Zereketh the Unbound' WHERE `entry`=494;
UPDATE `instance_encounters` SET `mapId`=552, `difficulty`=1, `encounterName`='Zereketh the Unbound' WHERE `entry`=495;
UPDATE `instance_encounters` SET `mapId`=552, `encounterIndex`=1, `encounterName`='Dalliah the Doomsayer' WHERE `entry`=496;
UPDATE `instance_encounters` SET `mapId`=552, `difficulty`=1, `encounterIndex`=1, `encounterName`='Dalliah the Doomsayer' WHERE `entry`=497;
UPDATE `instance_encounters` SET `mapId`=552, `encounterIndex`=2, `encounterName`='Wrath-Scryer Soccothrates' WHERE `entry`=498;
UPDATE `instance_encounters` SET `mapId`=552, `difficulty`=1, `encounterIndex`=2, `encounterName`='Wrath-Scryer Soccothrates' WHERE `entry`=499;
UPDATE `instance_encounters` SET `mapId`=552, `encounterIndex`=3, `encounterName`='Harbinger Skyriss' WHERE `entry`=500;
UPDATE `instance_encounters` SET `mapId`=552, `difficulty`=1, `encounterIndex`=4, `encounterName`='Harbinger Skyriss' WHERE `entry`=501;
UPDATE `instance_encounters` SET `mapId`=553, `encounterName`='Commander Sarannis' WHERE `entry`=502;
UPDATE `instance_encounters` SET `mapId`=553, `difficulty`=1, `encounterName`='Commander Sarannis' WHERE `entry`=504;
UPDATE `instance_encounters` SET `mapId`=553, `encounterIndex`=1, `encounterName`='High Botanist Freywinn' WHERE `entry`=505;
UPDATE `instance_encounters` SET `mapId`=553, `difficulty`=1, `encounterIndex`=1, `encounterName`='High Botanist Freywinn' WHERE `entry`=506;
UPDATE `instance_encounters` SET `mapId`=553, `encounterIndex`=2, `encounterName`='Thorngrin the Tender' WHERE `entry`=507;
UPDATE `instance_encounters` SET `mapId`=553, `difficulty`=1, `encounterIndex`=2, `encounterName`='Thorngrin the Tender' WHERE `entry`=508;
UPDATE `instance_encounters` SET `mapId`=553, `encounterIndex`=3, `encounterName`='Laj' WHERE `entry`=509;
UPDATE `instance_encounters` SET `mapId`=553, `difficulty`=1, `encounterIndex`=3, `encounterName`='Laj' WHERE `entry`=510;
UPDATE `instance_encounters` SET `mapId`=553, `encounterIndex`=4, `encounterName`='Warp Splinter' WHERE `entry`=511;
UPDATE `instance_encounters` SET `mapId`=553, `difficulty`=1, `encounterIndex`=4, `encounterName`='Warp Splinter' WHERE `entry`=512;
UPDATE `instance_encounters` SET `mapId`=554, `encounterName`='Mechano-Lord Capacitus' WHERE `entry`=513;
UPDATE `instance_encounters` SET `mapId`=554, `difficulty`=1, `encounterName`='Mechano-Lord Capacitus' WHERE `entry`=514;
UPDATE `instance_encounters` SET `mapId`=554, `encounterIndex`=1, `encounterName`='Nethermancer Sepethrea' WHERE `entry`=515;
UPDATE `instance_encounters` SET `mapId`=554, `difficulty`=1, `encounterIndex`=1, `encounterName`='Nethermancer Sepethrea' WHERE `entry`=516;
UPDATE `instance_encounters` SET `mapId`=554, `encounterIndex`=2, `encounterName`='Pathaleon the Calculator' WHERE `entry`=517;
UPDATE `instance_encounters` SET `mapId`=554, `difficulty`=1, `encounterIndex`=2, `encounterName`='Pathaleon the Calculator' WHERE `entry`=518;
UPDATE `instance_encounters` SET `mapId`=34, `encounterName`='Targorr the Dread' WHERE `entry`=536;
UPDATE `instance_encounters` SET `mapId`=34, `encounterIndex`=1, `encounterName`='Kam Deepfury' WHERE `entry`=537;
UPDATE `instance_encounters` SET `mapId`=34, `encounterIndex`=2, `encounterName`='Hamhock' WHERE `entry`=538;
UPDATE `instance_encounters` SET `mapId`=34, `encounterIndex`=3, `encounterName`='Bazil Thredd' WHERE `entry`=539;
UPDATE `instance_encounters` SET `mapId`=34, `encounterIndex`=4, `encounterName`='Dextren Ward' WHERE `entry`=540;
UPDATE `instance_encounters` SET `mapId`=70, `encounterName`='Revelosh' WHERE `entry`=547;
UPDATE `instance_encounters` SET `mapId`=70, `encounterIndex`=1, `encounterName`='The Lost Dwarves' WHERE `entry`=548;
UPDATE `instance_encounters` SET `mapId`=70, `encounterIndex`=2, `encounterName`='Ironaya' WHERE `entry`=549;
UPDATE `instance_encounters` SET `mapId`=70, `encounterIndex`=4, `encounterName`='Ancient Stone Keeper' WHERE `entry`=551;
UPDATE `instance_encounters` SET `mapId`=70, `encounterIndex`=5, `encounterName`='Galgann Firehammer' WHERE `entry`=552;
UPDATE `instance_encounters` SET `mapId`=70, `encounterIndex`=6, `encounterName`='Grimlok' WHERE `entry`=553;
UPDATE `instance_encounters` SET `mapId`=70, `encounterIndex`=7, `encounterName`='Archaedas' WHERE `entry`=554;
UPDATE `instance_encounters` SET `mapId`=43, `encounterName`='Lady Anacondra' WHERE `entry`=585;
UPDATE `instance_encounters` SET `mapId`=43, `encounterIndex`=1, `encounterName`='Lord Cobrahn' WHERE `entry`=586;
UPDATE `instance_encounters` SET `mapId`=43, `encounterIndex`=2, `encounterName`='Kresh' WHERE `entry`=587;
UPDATE `instance_encounters` SET `mapId`=43, `encounterIndex`=3, `encounterName`='Lord Pythas' WHERE `entry`=588;
UPDATE `instance_encounters` SET `mapId`=43, `encounterIndex`=4, `encounterName`='Skum' WHERE `entry`=589;
UPDATE `instance_encounters` SET `mapId`=43, `encounterIndex`=5, `encounterName`='Lord Serpentis' WHERE `entry`=590;
UPDATE `instance_encounters` SET `mapId`=43, `encounterIndex`=6, `encounterName`='Verdan the Everliving' WHERE `entry`=591;
UPDATE `instance_encounters` SET `mapId`=43, `encounterIndex`=7, `encounterName`='Mutanus the Devourer' WHERE `entry`=592;
UPDATE `instance_encounters` SET `mapId`=209, `encounterName`='Hydromancer Velratha' WHERE `entry`=593;
UPDATE `instance_encounters` SET `mapId`=209, `encounterIndex`=1, `encounterName`='Ghaz''rilla' WHERE `entry`=594;
UPDATE `instance_encounters` SET `mapId`=209, `encounterIndex`=2, `encounterName`='Antu''sul' WHERE `entry`=595;
UPDATE `instance_encounters` SET `mapId`=209, `encounterIndex`=3, `encounterName`='Theka the Martyr' WHERE `entry`=596;
UPDATE `instance_encounters` SET `mapId`=209, `encounterIndex`=4, `encounterName`='Witch Doctor Zum''rah' WHERE `entry`=597;
UPDATE `instance_encounters` SET `mapId`=209, `encounterIndex`=5, `encounterName`='Nekrum Gutchewer' WHERE `entry`=598;
UPDATE `instance_encounters` SET `mapId`=209, `encounterIndex`=6, `encounterName`='Shadowpriest Sezz''ziz' WHERE `entry`=599;
UPDATE `instance_encounters` SET `mapId`=209, `encounterIndex`=7, `encounterName`='Chief Ukorz Sandscalp' WHERE `entry`=600;
UPDATE `instance_encounters` SET `mapId`=564, `encounterName`='High Warlord Naj''entus' WHERE `entry`=601;
UPDATE `instance_encounters` SET `mapId`=564, `encounterIndex`=1, `encounterName`='Supremus' WHERE `entry`=602;
UPDATE `instance_encounters` SET `mapId`=564, `encounterIndex`=2, `encounterName`='Shade of Akama' WHERE `entry`=603;
UPDATE `instance_encounters` SET `mapId`=564, `encounterIndex`=3, `encounterName`='Teron Gorefiend' WHERE `entry`=604;
UPDATE `instance_encounters` SET `mapId`=564, `encounterIndex`=4, `encounterName`='Gurtogg Bloodboil' WHERE `entry`=605;
UPDATE `instance_encounters` SET `mapId`=564, `encounterIndex`=5, `encounterName`='Reliquary of Souls' WHERE `entry`=606;
UPDATE `instance_encounters` SET `mapId`=564, `encounterIndex`=6, `encounterName`='Mother Shahraz' WHERE `entry`=607;
UPDATE `instance_encounters` SET `mapId`=564, `encounterIndex`=7, `encounterName`='The Illidari Council' WHERE `entry`=608;
UPDATE `instance_encounters` SET `mapId`=564, `encounterIndex`=8, `encounterName`='Illidan Stormrage' WHERE `entry`=609;
UPDATE `instance_encounters` SET `mapId`=469, `encounterName`='Razorgore the Untamed' WHERE `entry`=610;
UPDATE `instance_encounters` SET `mapId`=469, `encounterIndex`=1, `encounterName`='Vaelastrasz the Corrupt' WHERE `entry`=611;
UPDATE `instance_encounters` SET `mapId`=469, `encounterIndex`=2, `encounterName`='Broodlord Lashlayer' WHERE `entry`=612;
UPDATE `instance_encounters` SET `mapId`=469, `encounterIndex`=3, `encounterName`='Firemaw' WHERE `entry`=613;
UPDATE `instance_encounters` SET `mapId`=469, `encounterIndex`=4, `encounterName`='Ebonroc' WHERE `entry`=614;
UPDATE `instance_encounters` SET `mapId`=469, `encounterIndex`=5, `encounterName`='Flamegor' WHERE `entry`=615;
UPDATE `instance_encounters` SET `mapId`=469, `encounterIndex`=6, `encounterName`='Chromaggus' WHERE `entry`=616;
UPDATE `instance_encounters` SET `mapId`=469, `encounterIndex`=7, `encounterName`='Nefarian' WHERE `entry`=617;
UPDATE `instance_encounters` SET `mapId`=534, `encounterName`='Rage Winterchill' WHERE `entry`=618;
UPDATE `instance_encounters` SET `mapId`=534, `encounterIndex`=1, `encounterName`='Anetheron' WHERE `entry`=619;
UPDATE `instance_encounters` SET `mapId`=534, `encounterIndex`=2, `encounterName`='Kaz''rogal' WHERE `entry`=620;
UPDATE `instance_encounters` SET `mapId`=534, `encounterIndex`=3, `encounterName`='Azgalor' WHERE `entry`=621;
UPDATE `instance_encounters` SET `mapId`=534, `encounterIndex`=4, `encounterName`='Archimonde' WHERE `entry`=622;
UPDATE `instance_encounters` SET `mapId`=548, `encounterName`='Hydross the Unstable' WHERE `entry`=623;
UPDATE `instance_encounters` SET `mapId`=548, `encounterIndex`=1, `encounterName`='The Lurker Below' WHERE `entry`=624;
UPDATE `instance_encounters` SET `mapId`=548, `encounterIndex`=2, `encounterName`='Leotheras the Blind' WHERE `entry`=625;
UPDATE `instance_encounters` SET `mapId`=548, `encounterIndex`=3, `encounterName`='Fathom-Lord Karathress' WHERE `entry`=626;
UPDATE `instance_encounters` SET `mapId`=548, `encounterIndex`=4, `encounterName`='Morogrim Tidewalker' WHERE `entry`=627;
UPDATE `instance_encounters` SET `mapId`=548, `encounterIndex`=5, `encounterName`='Lady Vashj' WHERE `entry`=628;
UPDATE `instance_encounters` SET `mapId`=565, `encounterName`='High King Maulgar' WHERE `entry`=649;
UPDATE `instance_encounters` SET `mapId`=565, `encounterIndex`=1, `encounterName`='Gruul the Dragonkiller' WHERE `entry`=650;
UPDATE `instance_encounters` SET `mapId`=544, `encounterName`='Magtheridon' WHERE `entry`=651;
UPDATE `instance_encounters` SET `mapId`=532, `encounterName`='Attumen the Huntsman' WHERE `entry`=652;
UPDATE `instance_encounters` SET `mapId`=532, `encounterIndex`=1, `encounterName`='Moroes' WHERE `entry`=653;
UPDATE `instance_encounters` SET `mapId`=532, `encounterIndex`=2, `encounterName`='Maiden of the Virtue' WHERE `entry`=654;
UPDATE `instance_encounters` SET `mapId`=532, `encounterIndex`=3, `encounterName`='Opera Event' WHERE `entry`=655;
UPDATE `instance_encounters` SET `mapId`=532, `encounterIndex`=4, `encounterName`='The Curator' WHERE `entry`=656;
UPDATE `instance_encounters` SET `mapId`=532, `encounterIndex`=5, `encounterName`='Terestian Illhoof' WHERE `entry`=657;
UPDATE `instance_encounters` SET `mapId`=532, `encounterIndex`=6, `encounterName`='Shade of Aran' WHERE `entry`=658;
UPDATE `instance_encounters` SET `mapId`=532, `encounterIndex`=7, `encounterName`='Netherspite' WHERE `entry`=659;
UPDATE `instance_encounters` SET `mapId`=532, `encounterIndex`=8, `encounterName`='Chess Event' WHERE `entry`=660;
UPDATE `instance_encounters` SET `mapId`=532, `encounterIndex`=9, `encounterName`='Prince Malchezaar' WHERE `entry`=661;
UPDATE `instance_encounters` SET `mapId`=532, `encounterIndex`=10, `encounterName`='Nightbane' WHERE `entry`=662;
UPDATE `instance_encounters` SET `mapId`=409, `encounterName`='Lucifron' WHERE `entry`=663;
UPDATE `instance_encounters` SET `mapId`=409, `encounterIndex`=1, `encounterName`='Magmadar' WHERE `entry`=664;
UPDATE `instance_encounters` SET `mapId`=409, `encounterIndex`=2, `encounterName`='Gehennas' WHERE `entry`=665;
UPDATE `instance_encounters` SET `mapId`=409, `encounterIndex`=3, `encounterName`='Garr' WHERE `entry`=666;
UPDATE `instance_encounters` SET `mapId`=409, `encounterIndex`=4, `encounterName`='Shazzrah' WHERE `entry`=667;
UPDATE `instance_encounters` SET `mapId`=409, `encounterIndex`=5, `encounterName`='Baron Geddon' WHERE `entry`=668;
UPDATE `instance_encounters` SET `mapId`=409, `encounterIndex`=6, `encounterName`='Sulfuron Harbinger' WHERE `entry`=669;
UPDATE `instance_encounters` SET `mapId`=409, `encounterIndex`=7, `encounterName`='Golemagg the Incinerator' WHERE `entry`=670;
UPDATE `instance_encounters` SET `mapId`=409, `encounterIndex`=8, `encounterName`='Majordomo Executus' WHERE `entry`=671;
UPDATE `instance_encounters` SET `mapId`=409, `encounterIndex`=9, `encounterName`='Ragnaros' WHERE `entry`=672;
UPDATE `instance_encounters` SET `mapId`=533, `encounterName`='Anub''Rekhan' WHERE `entry`=673;
UPDATE `instance_encounters` SET `mapId`=533, `encounterIndex`=1, `encounterName`='Grand Widow Faerlina' WHERE `entry`=677;
UPDATE `instance_encounters` SET `mapId`=533, `encounterIndex`=2, `encounterName`='Maexxna' WHERE `entry`=679;
UPDATE `instance_encounters` SET `mapId`=533, `encounterIndex`=3, `encounterName`='Noth the Plaguebringer' WHERE `entry`=681;
UPDATE `instance_encounters` SET `mapId`=533, `encounterIndex`=4, `encounterName`='Heigan the Unclean' WHERE `entry`=683;
UPDATE `instance_encounters` SET `mapId`=533, `encounterIndex`=5, `encounterName`='Loatheb' WHERE `entry`=685;
UPDATE `instance_encounters` SET `mapId`=533, `encounterIndex`=6, `encounterName`='Instructor Razuvious' WHERE `entry`=687;
UPDATE `instance_encounters` SET `mapId`=533, `encounterIndex`=7, `encounterName`='Gothik the Harvester' WHERE `entry`=690;
UPDATE `instance_encounters` SET `mapId`=533, `encounterIndex`=8, `encounterName`='The Four Horsemen' WHERE `entry`=692;
UPDATE `instance_encounters` SET `mapId`=533, `encounterIndex`=9, `encounterName`='Patchwerk' WHERE `entry`=694;
UPDATE `instance_encounters` SET `mapId`=533, `encounterIndex`=10, `encounterName`='Grobbulus' WHERE `entry`=696;
UPDATE `instance_encounters` SET `mapId`=533, `encounterIndex`=11, `encounterName`='Gluth' WHERE `entry`=698;
UPDATE `instance_encounters` SET `mapId`=533, `encounterIndex`=12, `encounterName`='Thaddius' WHERE `entry`=700;
UPDATE `instance_encounters` SET `mapId`=533, `encounterIndex`=13, `encounterName`='Sapphiron' WHERE `entry`=702;
UPDATE `instance_encounters` SET `mapId`=533, `encounterIndex`=14, `encounterName`='Kel''Thuzad' WHERE `entry`=704;
UPDATE `instance_encounters` SET `mapId`=249, `encounterName`='Onyxia' WHERE `entry`=707;
UPDATE `instance_encounters` SET `mapId`=531, `encounterName`='The Prophet Skeram' WHERE `entry`=709;
UPDATE `instance_encounters` SET `mapId`=531, `encounterIndex`=1, `encounterName`='Silithid Royalty' WHERE `entry`=710;
UPDATE `instance_encounters` SET `mapId`=531, `encounterIndex`=2, `encounterName`='Battleguard Sartura' WHERE `entry`=711;
UPDATE `instance_encounters` SET `mapId`=531, `encounterIndex`=3, `encounterName`='Fankriss the Unyielding' WHERE `entry`=712;
UPDATE `instance_encounters` SET `mapId`=531, `encounterIndex`=4, `encounterName`='Viscidus' WHERE `entry`=713;
UPDATE `instance_encounters` SET `mapId`=531, `encounterIndex`=5, `encounterName`='Princess Huhuran' WHERE `entry`=714;
UPDATE `instance_encounters` SET `mapId`=531, `encounterIndex`=6, `encounterName`='Twin Emperors' WHERE `entry`=715;
UPDATE `instance_encounters` SET `mapId`=531, `encounterIndex`=7, `encounterName`='Ouro' WHERE `entry`=716;
UPDATE `instance_encounters` SET `mapId`=531, `encounterIndex`=8, `encounterName`='C''thun' WHERE `entry`=717;
UPDATE `instance_encounters` SET `mapId`=509, `encounterName`='Kurinnaxx' WHERE `entry`=718;
UPDATE `instance_encounters` SET `mapId`=509, `encounterIndex`=1, `encounterName`='General Rajaxx' WHERE `entry`=719;
UPDATE `instance_encounters` SET `mapId`=509, `encounterIndex`=2, `encounterName`='Moam' WHERE `entry`=720;
UPDATE `instance_encounters` SET `mapId`=509, `encounterIndex`=3, `encounterName`='Buru the Gorger' WHERE `entry`=721;
UPDATE `instance_encounters` SET `mapId`=509, `encounterIndex`=4, `encounterName`='Ayamiss the Hunter' WHERE `entry`=722;
UPDATE `instance_encounters` SET `mapId`=509, `encounterIndex`=5, `encounterName`='Ossirian the Unscarred' WHERE `entry`=723;
UPDATE `instance_encounters` SET `mapId`=580, `encounterName`='Kalecgos' WHERE `entry`=724;
UPDATE `instance_encounters` SET `mapId`=580, `encounterIndex`=1, `encounterName`='GiBrutalluslnid' WHERE `entry`=725;
UPDATE `instance_encounters` SET `mapId`=580, `encounterIndex`=2, `encounterName`='GilFelmystnid' WHERE `entry`=726;
UPDATE `instance_encounters` SET `mapId`=580, `encounterIndex`=3, `encounterName`='Eredar Twins' WHERE `entry`=727;
UPDATE `instance_encounters` SET `mapId`=580, `encounterIndex`=4, `encounterName`='M''uru' WHERE `entry`=728;
UPDATE `instance_encounters` SET `mapId`=580, `encounterIndex`=5, `encounterName`='Kil''jaeden' WHERE `entry`=729;
UPDATE `instance_encounters` SET `mapId`=550, `encounterName`='Al''ar' WHERE `entry`=730;
UPDATE `instance_encounters` SET `mapId`=550, `encounterIndex`=1, `encounterName`='Void Reaver' WHERE `entry`=731;
UPDATE `instance_encounters` SET `mapId`=550, `encounterIndex`=2, `encounterName`='High Astromancer Solarian' WHERE `entry`=732;
UPDATE `instance_encounters` SET `mapId`=550, `encounterIndex`=3, `encounterName`='Kael''thas Sunstrider' WHERE `entry`=733;
UPDATE `instance_encounters` SET `mapId`=568, `encounterName`='Akil''zon' WHERE `entry`=778;
UPDATE `instance_encounters` SET `mapId`=568, `encounterIndex`=1, `encounterName`='Nalorakk' WHERE `entry`=779;
UPDATE `instance_encounters` SET `mapId`=568, `encounterIndex`=2, `encounterName`='Jan''alai' WHERE `entry`=780;
UPDATE `instance_encounters` SET `mapId`=568, `encounterIndex`=3, `encounterName`='Halazzi' WHERE `entry`=781;
UPDATE `instance_encounters` SET `mapId`=568, `encounterIndex`=4, `encounterName`='Hex Lord Malacrass' WHERE `entry`=782;
UPDATE `instance_encounters` SET `mapId`=568, `encounterIndex`=5, `encounterName`='Zul''jin' WHERE `entry`=783;
UPDATE `instance_encounters` SET `mapId`=309, `encounterName`='High Priest Venoxis' WHERE `entry`=784;
UPDATE `instance_encounters` SET `mapId`=309, `encounterIndex`=1, `encounterName`='High Priestess Jeklik' WHERE `entry`=785;
UPDATE `instance_encounters` SET `mapId`=309, `encounterIndex`=2, `encounterName`='High Priestess Mar''li' WHERE `entry`=786;
UPDATE `instance_encounters` SET `mapId`=309, `encounterIndex`=3, `encounterName`='Bloodlord Mandokir' WHERE `entry`=787;
UPDATE `instance_encounters` SET `mapId`=309, `encounterIndex`=4, `encounterName`='Edge of Madness' WHERE `entry`=788;
UPDATE `instance_encounters` SET `mapId`=309, `encounterIndex`=5, `encounterName`='High Priest Thekal' WHERE `entry`=789;
UPDATE `instance_encounters` SET `mapId`=309, `encounterIndex`=6, `encounterName`='Gahz''ranka' WHERE `entry`=790;
UPDATE `instance_encounters` SET `mapId`=309, `encounterIndex`=7, `encounterName`='High Priestess Arlokk' WHERE `entry`=791;
UPDATE `instance_encounters` SET `mapId`=309, `encounterIndex`=8, `encounterName`='Jin''do the Hexxer' WHERE `entry`=792;
UPDATE `instance_encounters` SET `mapId`=309, `encounterIndex`=9, `encounterName`='Hakkar' WHERE `entry`=793;
UPDATE `instance_encounters` SET `mapId`=47, `encounterIndex`=5, `encounterName`='Agathelos the Raging' WHERE `entry`=883;
